[package]
name = "1legendrblx/repertoire"
authors = ["Legend <noahross06@gmail.com>", "Jaeymo <jaey.cyber@gmail.com>"]
description = "Front-end orchestrator"
version = "1.1.0"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "README.md"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
Promise = "howmanysmall/typed-promise@4.0.6"